services:
  - type: web
    name: telegram-2d-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: TOKEN
        value: 7753083556:AAHGzsJ5YnOYTUSU7_Xygo6kUrF7KnQwMlk
      - key: ADMIN_ID
        value: 1392912618
      - key: GROUP_ID
        value: your-group-id
